package fr.jbdev.domaine;

// Generated 7 janv. 2016 21:47:57 by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Achats generated by hbm2java
 */
@Entity
@Table(name = "ACHATS", catalog = "facturierDeux")
public class Achats implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 1L;
    private Integer numAchats;
    private TypeDePaiment typeDePaiment;
    private Commandes commandes;
    private Date dateAchats;
    private double accomte;
    private Double tvaRembourssable;

    public Achats() {
    }

    public Achats(TypeDePaiment typeDePaiment, Commandes commandes,
	    Date dateAchats, double accomte) {
	this.typeDePaiment = typeDePaiment;
	this.commandes = commandes;
	this.dateAchats = dateAchats;
	this.accomte = accomte;
    }

    public Achats(TypeDePaiment typeDePaiment, Commandes commandes,
	    Date dateAchats, double accomte, Double tvaRembourssable) {
	this.typeDePaiment = typeDePaiment;
	this.commandes = commandes;
	this.dateAchats = dateAchats;
	this.accomte = accomte;
	this.tvaRembourssable = tvaRembourssable;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "NumAchats", unique = true, nullable = false)
    public Integer getNumAchats() {
	return this.numAchats;
    }

    public void setNumAchats(Integer numAchats) {
	this.numAchats = numAchats;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "NumTypeDePaiment", nullable = false)
    public TypeDePaiment getTypeDePaiment() {
	return this.typeDePaiment;
    }

    public void setTypeDePaiment(TypeDePaiment typeDePaiment) {
	this.typeDePaiment = typeDePaiment;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "NumCommade", nullable = false)
    public Commandes getCommandes() {
	return this.commandes;
    }

    public void setCommandes(Commandes commandes) {
	this.commandes = commandes;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "DateAchats", nullable = false, length = 10)
    public Date getDateAchats() {
	return this.dateAchats;
    }

    public void setDateAchats(Date dateAchats) {
	this.dateAchats = dateAchats;
    }

    @Column(name = "Accomte", nullable = false, precision = 22, scale = 0)
    public double getAccomte() {
	return this.accomte;
    }

    public void setAccomte(double accomte) {
	this.accomte = accomte;
    }

    @Column(name = "TvaRembourssable", precision = 22, scale = 0)
    public Double getTvaRembourssable() {
	return this.tvaRembourssable;
    }

    public void setTvaRembourssable(Double tvaRembourssable) {
	this.tvaRembourssable = tvaRembourssable;
    }

}
