package fr.jbdev.domaine;

// Generated 7 janv. 2016 21:47:57 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Adresses generated by hbm2java
 */
@Entity
@Table(name = "ADRESSES", catalog = "facturierDeux")
public class Adresses implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 1L;
    private String numAdresse;
    private int numero;
    private String voie;
    private String codePostal;
    private String ville;
    private Set<Personnes> personneses = new HashSet<Personnes>(0);
    private Set<Entreprises> entrepriseses = new HashSet<Entreprises>(0);

    public Adresses() {
    }

    public Adresses(String numAdresse, int numero, String voie,
	    String codePostal, String ville) {
	this.numAdresse = numAdresse;
	this.numero = numero;
	this.voie = voie;
	this.codePostal = codePostal;
	this.ville = ville;
    }

    public Adresses(String numAdresse, int numero, String voie,
	    String codePostal, String ville, Set<Personnes> personneses,
	    Set<Entreprises> entrepriseses) {
	this.numAdresse = numAdresse;
	this.numero = numero;
	this.voie = voie;
	this.codePostal = codePostal;
	this.ville = ville;
	this.personneses = personneses;
	this.entrepriseses = entrepriseses;
    }

    @Id
    @Column(name = "NumAdresse", unique = true, nullable = false, length = 25)
    public String getNumAdresse() {
	return this.numAdresse;
    }

    public void setNumAdresse(String numAdresse) {
	this.numAdresse = numAdresse;
    }

    @Column(name = "numero", nullable = false)
    public int getNumero() {
	return this.numero;
    }

    public void setNumero(int numero) {
	this.numero = numero;
    }

    @Column(name = "voie", nullable = false, length = 65535)
    public String getVoie() {
	return this.voie;
    }

    public void setVoie(String voie) {
	this.voie = voie;
    }

    @Column(name = "CodePostal", nullable = false, length = 5)
    public String getCodePostal() {
	return this.codePostal;
    }

    public void setCodePostal(String codePostal) {
	this.codePostal = codePostal;
    }

    @Column(name = "Ville", nullable = false, length = 25)
    public String getVille() {
	return this.ville;
    }

    public void setVille(String ville) {
	this.ville = ville;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "adresses")
    public Set<Personnes> getPersonneses() {
	return this.personneses;
    }

    public void setPersonneses(Set<Personnes> personneses) {
	this.personneses = personneses;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "adresses")
    public Set<Entreprises> getEntrepriseses() {
	return this.entrepriseses;
    }

    public void setEntrepriseses(Set<Entreprises> entrepriseses) {
	this.entrepriseses = entrepriseses;
    }

}
