package fr.jbdev.domaine;

// Generated 7 janv. 2016 21:47:57 by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Categories generated by hbm2java
 */
@Entity
@Table(name = "CATEGORIES", catalog = "facturierDeux")
public class Categories implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 1L;
    private Integer numCategorie;
    private Entreprises entreprises;
    private String nom;
    private String description;
    private Set<DevisProduits> devisProduitses = new HashSet<DevisProduits>(0);
    private Set<Produits> produitses = new HashSet<Produits>(0);

    public Categories() {
    }

    public Categories(Entreprises entreprises, String nom) {
	this.entreprises = entreprises;
	this.nom = nom;
    }

    public Categories(Entreprises entreprises, String nom, String description,
	    Set<DevisProduits> devisProduitses, Set<Produits> produitses) {
	this.entreprises = entreprises;
	this.nom = nom;
	this.description = description;
	this.devisProduitses = devisProduitses;
	this.produitses = produitses;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "NumCategorie", unique = true, nullable = false)
    public Integer getNumCategorie() {
	return this.numCategorie;
    }

    public void setNumCategorie(Integer numCategorie) {
	this.numCategorie = numCategorie;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "NumSiret", nullable = false)
    public Entreprises getEntreprises() {
	return this.entreprises;
    }

    public void setEntreprises(Entreprises entreprises) {
	this.entreprises = entreprises;
    }

    @Column(name = "Nom", nullable = false, length = 25)
    public String getNom() {
	return this.nom;
    }

    public void setNom(String nom) {
	this.nom = nom;
    }

    @Column(name = "Description", length = 25)
    public String getDescription() {
	return this.description;
    }

    public void setDescription(String description) {
	this.description = description;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "categories")
    public Set<DevisProduits> getDevisProduitses() {
	return this.devisProduitses;
    }

    public void setDevisProduitses(Set<DevisProduits> devisProduitses) {
	this.devisProduitses = devisProduitses;
    }

    @OneToMany(fetch = FetchType.EAGER, mappedBy = "categories")
    public Set<Produits> getProduitses() {
	return this.produitses;
    }

    public void setProduitses(Set<Produits> produitses) {
	this.produitses = produitses;
    }

}
