package fr.jbdev.domaine;

// Generated 7 janv. 2016 21:47:57 by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Clients generated by hbm2java
 */
@Entity
@Table(name = "CLIENTS", catalog = "facturierDeux")
public class Clients implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 1L;
    private Integer numClient;
    private Personnes personnes;
    private Entreprises entreprises;
    private String email;
    private Double solde;
    private String numSiretClient;
    private Set<Devis> devises = new HashSet<Devis>(0);

    public Clients() {
    }

    public Clients(Personnes personnes, Entreprises entreprises, String email) {
	this.personnes = personnes;
	this.entreprises = entreprises;
	this.email = email;
    }

    public Clients(Personnes personnes, Entreprises entreprises, String email,
	    Double solde, String numSiretClient, Set<Devis> devises) {
	this.personnes = personnes;
	this.entreprises = entreprises;
	this.email = email;
	this.solde = solde;
	this.numSiretClient = numSiretClient;
	this.devises = devises;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "NumClient", unique = true, nullable = false)
    public Integer getNumClient() {
	return this.numClient;
    }

    public void setNumClient(Integer numClient) {
	this.numClient = numClient;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "NumPersonne", nullable = false)
    public Personnes getPersonnes() {
	return this.personnes;
    }

    public void setPersonnes(Personnes personnes) {
	this.personnes = personnes;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "NumSiret", nullable = false)
    public Entreprises getEntreprises() {
	return this.entreprises;
    }

    public void setEntreprises(Entreprises entreprises) {
	this.entreprises = entreprises;
    }

    @Column(name = "Email", nullable = false, length = 254)
    public String getEmail() {
	return this.email;
    }

    public void setEmail(String email) {
	this.email = email;
    }

    @Column(name = "Solde", precision = 22, scale = 0)
    public Double getSolde() {
	return this.solde;
    }

    public void setSolde(Double solde) {
	this.solde = solde;
    }

    @Column(name = "NumSiretClient", length = 32)
    public String getNumSiretClient() {
	return this.numSiretClient;
    }

    public void setNumSiretClient(String numSiretClient) {
	this.numSiretClient = numSiretClient;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "clients")
    public Set<Devis> getDevises() {
	return this.devises;
    }

    public void setDevises(Set<Devis> devises) {
	this.devises = devises;
    }

}
