package fr.jbdev.domaine;

// Generated 7 janv. 2016 21:47:57 by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Commandes generated by hbm2java
 */
@Entity
@Table(name = "COMMANDES", catalog = "facturierDeux")
public class Commandes implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 1L;
    private Integer numCommade;
    private Entreprises entreprises;
    private Fournisseurs fournisseurs;
    private Date dateCommande;
    private double solde;
    private double tva;
    private boolean valide;
    private Set<Achats> achatses = new HashSet<Achats>(0);
    private Set<Contient> contients = new HashSet<Contient>(0);

    public Commandes() {
    }

    public Commandes(Entreprises entreprises, Fournisseurs fournisseurs,
	    Date dateCommande, double solde, double tva, boolean valide) {
	this.entreprises = entreprises;
	this.fournisseurs = fournisseurs;
	this.dateCommande = dateCommande;
	this.solde = solde;
	this.tva = tva;
	this.valide = valide;
    }

    public Commandes(Entreprises entreprises, Fournisseurs fournisseurs,
	    Date dateCommande, double solde, double tva, boolean valide,
	    Set<Achats> achatses, Set<Contient> contients) {
	this.entreprises = entreprises;
	this.fournisseurs = fournisseurs;
	this.dateCommande = dateCommande;
	this.solde = solde;
	this.tva = tva;
	this.valide = valide;
	this.achatses = achatses;
	this.contients = contients;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "NumCommade", unique = true, nullable = false)
    public Integer getNumCommade() {
	return this.numCommade;
    }

    public void setNumCommade(Integer numCommade) {
	this.numCommade = numCommade;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "NumSiret", nullable = false)
    public Entreprises getEntreprises() {
	return this.entreprises;
    }

    public void setEntreprises(Entreprises entreprises) {
	this.entreprises = entreprises;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "NumFournisseur", nullable = false)
    public Fournisseurs getFournisseurs() {
	return this.fournisseurs;
    }

    public void setFournisseurs(Fournisseurs fournisseurs) {
	this.fournisseurs = fournisseurs;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "DateCommande", nullable = false, length = 10)
    public Date getDateCommande() {
	return this.dateCommande;
    }

    public void setDateCommande(Date dateCommande) {
	this.dateCommande = dateCommande;
    }

    @Column(name = "Solde", nullable = false, precision = 22, scale = 0)
    public double getSolde() {
	return this.solde;
    }

    public void setSolde(double solde) {
	this.solde = solde;
    }

    @Column(name = "Tva", nullable = false, precision = 22, scale = 0)
    public double getTva() {
	return this.tva;
    }

    public void setTva(double tva) {
	this.tva = tva;
    }

    @Column(name = "Valide", nullable = false)
    public boolean isValide() {
	return this.valide;
    }

    public void setValide(boolean valide) {
	this.valide = valide;
    }

    @OneToMany(fetch = FetchType.EAGER, mappedBy = "commandes")
    public Set<Achats> getAchatses() {
	return this.achatses;
    }

    public void setAchatses(Set<Achats> achatses) {
	this.achatses = achatses;
    }

    @OneToMany(fetch = FetchType.EAGER, mappedBy = "commandes")
    public Set<Contient> getContients() {
	return this.contients;
    }

    public void setContients(Set<Contient> contients) {
	this.contients = contients;
    }

}
