package fr.jbdev.domaine;

// Generated 7 janv. 2016 21:47:57 by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Contient generated by hbm2java
 */
@Entity
@Table(name = "CONTIENT", catalog = "facturierDeux")
public class Contient implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 1L;
    private Integer numContient;
    private Produits produits;
    private Tva tva;
    private Commandes commandes;
    private float quantite;

    public Contient() {
    }

    public Contient(Produits produits, Tva tva, Commandes commandes,
	    float quantite) {
	this.produits = produits;
	this.tva = tva;
	this.commandes = commandes;
	this.quantite = quantite;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "NumContient", unique = true, nullable = false)
    public Integer getNumContient() {
	return this.numContient;
    }

    public void setNumContient(Integer numContient) {
	this.numContient = numContient;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "NumProduits", nullable = false)
    public Produits getProduits() {
	return this.produits;
    }

    public void setProduits(Produits produits) {
	this.produits = produits;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "NumTva", nullable = false)
    public Tva getTva() {
	return this.tva;
    }

    public void setTva(Tva tva) {
	this.tva = tva;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "NumCommande", nullable = false)
    public Commandes getCommandes() {
	return this.commandes;
    }

    public void setCommandes(Commandes commandes) {
	this.commandes = commandes;
    }

    @Column(name = "Quantite", nullable = false, precision = 12, scale = 0)
    public float getQuantite() {
	return this.quantite;
    }

    public void setQuantite(float quantite) {
	this.quantite = quantite;
    }

}
