package fr.jbdev.domaine;

// Generated 7 janv. 2016 21:47:57 by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Devis generated by hbm2java
 */
@Entity
@Table(name = "DEVIS", catalog = "facturierDeux")
public class Devis implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 1L;
    private Integer numDevis;
    private Entreprises entreprises;
    private Clients clients;
    private String numero;
    private String mentions;
    private Date dateDevis;
    private Date dateFinDevis;
    private Float remiseGlobal;
    private Set<DevisProduits> devisProduitses = new HashSet<DevisProduits>(0);
    private Set<Factures> factureses = new HashSet<Factures>(0);

    public Devis() {
    }

    public Devis(Entreprises entreprises, Clients clients, String numero,
	    Date dateDevis, Date dateFinDevis) {
	this.entreprises = entreprises;
	this.clients = clients;
	this.numero = numero;
	this.dateDevis = dateDevis;
	this.dateFinDevis = dateFinDevis;
    }

    public Devis(Entreprises entreprises, Clients clients, String numero,
	    String mentions, Date dateDevis, Date dateFinDevis,
	    Float remiseGlobal, Set<DevisProduits> devisProduitses,
	    Set<Factures> factureses) {
	this.entreprises = entreprises;
	this.clients = clients;
	this.numero = numero;
	this.mentions = mentions;
	this.dateDevis = dateDevis;
	this.dateFinDevis = dateFinDevis;
	this.remiseGlobal = remiseGlobal;
	this.devisProduitses = devisProduitses;
	this.factureses = factureses;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "NumDevis", unique = true, nullable = false)
    public Integer getNumDevis() {
	return this.numDevis;
    }

    public void setNumDevis(Integer numDevis) {
	this.numDevis = numDevis;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "NumSiret", nullable = false)
    public Entreprises getEntreprises() {
	return this.entreprises;
    }

    public void setEntreprises(Entreprises entreprises) {
	this.entreprises = entreprises;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "NumClient", nullable = false)
    public Clients getClients() {
	return this.clients;
    }

    public void setClients(Clients clients) {
	this.clients = clients;
    }

    @Column(name = "Numero", nullable = false, length = 25)
    public String getNumero() {
	return this.numero;
    }

    public void setNumero(String numero) {
	this.numero = numero;
    }

    @Column(name = "Mentions", length = 65535)
    public String getMentions() {
	return this.mentions;
    }

    public void setMentions(String mentions) {
	this.mentions = mentions;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "DateDevis", nullable = false, length = 10)
    public Date getDateDevis() {
	return this.dateDevis;
    }

    public void setDateDevis(Date dateDevis) {
	this.dateDevis = dateDevis;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "DateFinDevis", nullable = false, length = 10)
    public Date getDateFinDevis() {
	return this.dateFinDevis;
    }

    public void setDateFinDevis(Date dateFinDevis) {
	this.dateFinDevis = dateFinDevis;
    }

    @Column(name = "RemiseGlobal", precision = 12, scale = 0)
    public Float getRemiseGlobal() {
	return this.remiseGlobal;
    }

    public void setRemiseGlobal(Float remiseGlobal) {
	this.remiseGlobal = remiseGlobal;
    }

    @OneToMany(fetch = FetchType.EAGER, mappedBy = "devis")
    public Set<DevisProduits> getDevisProduitses() {
	return this.devisProduitses;
    }

    public void setDevisProduitses(Set<DevisProduits> devisProduitses) {
	this.devisProduitses = devisProduitses;
    }

    @OneToMany(fetch = FetchType.EAGER, mappedBy = "devis")
    public Set<Factures> getFactureses() {
	return this.factureses;
    }

    public void setFactureses(Set<Factures> factureses) {
	this.factureses = factureses;
    }

}
