package fr.jbdev.domaine;

// Generated 7 janv. 2016 21:47:57 by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Entrepots generated by hbm2java
 */
@Entity
@Table(name = "ENTREPOTS", catalog = "facturierDeux")
public class Entrepots implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 1L;
    private Integer numId;
    private Entreprises entreprises;
    private String numero;
    private String nom;
    private Set<Produits> produitses = new HashSet<Produits>(0);

    public Entrepots() {
    }

    public Entrepots(Entreprises entreprises, String numero, String nom) {
	this.entreprises = entreprises;
	this.numero = numero;
	this.nom = nom;
    }

    public Entrepots(Entreprises entreprises, String numero, String nom,
	    Set<Produits> produitses) {
	this.entreprises = entreprises;
	this.numero = numero;
	this.nom = nom;
	this.produitses = produitses;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "NumId", unique = true, nullable = false)
    public Integer getNumId() {
	return this.numId;
    }

    public void setNumId(Integer numId) {
	this.numId = numId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "NumSiret", nullable = false)
    public Entreprises getEntreprises() {
	return this.entreprises;
    }

    public void setEntreprises(Entreprises entreprises) {
	this.entreprises = entreprises;
    }

    @Column(name = "Numero", nullable = false, length = 25)
    public String getNumero() {
	return this.numero;
    }

    public void setNumero(String numero) {
	this.numero = numero;
    }

    @Column(name = "Nom", nullable = false, length = 32)
    public String getNom() {
	return this.nom;
    }

    public void setNom(String nom) {
	this.nom = nom;
    }

    @OneToMany(fetch = FetchType.EAGER, mappedBy = "entrepots")
    public Set<Produits> getProduitses() {
	return this.produitses;
    }

    public void setProduitses(Set<Produits> produitses) {
	this.produitses = produitses;
    }

}
