package fr.jbdev.domaine;

// Generated 7 janv. 2016 21:47:57 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ExercicecomptableId generated by hbm2java
 */
@Embeddable
public class ExercicecomptableId implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 1L;
    private int numId;
    private String numSiret;

    public ExercicecomptableId() {
    }

    public ExercicecomptableId(int numId, String numSiret) {
	this.numId = numId;
	this.numSiret = numSiret;
    }

    @Column(name = "NumId", nullable = false)
    public int getNumId() {
	return this.numId;
    }

    public void setNumId(int numId) {
	this.numId = numId;
    }

    @Column(name = "NumSiret", nullable = false, length = 32)
    public String getNumSiret() {
	return this.numSiret;
    }

    public void setNumSiret(String numSiret) {
	this.numSiret = numSiret;
    }

    @Override
    public boolean equals(Object other) {
	if ((this == other))
	    return true;
	if ((other == null))
	    return false;
	if (!(other instanceof ExercicecomptableId))
	    return false;
	ExercicecomptableId castOther = (ExercicecomptableId) other;

	return (this.getNumId() == castOther.getNumId())
		&& ((this.getNumSiret() == castOther.getNumSiret()) || (this
			.getNumSiret() != null
			&& castOther.getNumSiret() != null && this
			.getNumSiret().equals(castOther.getNumSiret())));
    }

    @Override
    public int hashCode() {
	int result = 17;

	result = 37 * result + this.getNumId();
	result = 37 * result
		+ (getNumSiret() == null ? 0 : this.getNumSiret().hashCode());
	return result;
    }

}
