package fr.jbdev.domaine;

// Generated 7 janv. 2016 21:47:57 by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Factures generated by hbm2java
 */
@Entity
@Table(name = "FACTURES", catalog = "facturierDeux")
public class Factures implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 1L;
    private Integer numFacture;
    private Devis devis;
    private String numero;
    private String mentions;
    private Date dateFacture;
    private Set<Vente> ventes = new HashSet<Vente>(0);

    public Factures() {
    }

    public Factures(Devis devis, String numero, Date dateFacture) {
	this.devis = devis;
	this.numero = numero;
	this.dateFacture = dateFacture;
    }

    public Factures(Devis devis, String numero, String mentions,
	    Date dateFacture, Set<Vente> ventes) {
	this.devis = devis;
	this.numero = numero;
	this.mentions = mentions;
	this.dateFacture = dateFacture;
	this.ventes = ventes;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "NumFacture", unique = true, nullable = false)
    public Integer getNumFacture() {
	return this.numFacture;
    }

    public void setNumFacture(Integer numFacture) {
	this.numFacture = numFacture;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "NumDevis", nullable = false)
    public Devis getDevis() {
	return this.devis;
    }

    public void setDevis(Devis devis) {
	this.devis = devis;
    }

    @Column(name = "Numero", nullable = false, length = 25)
    public String getNumero() {
	return this.numero;
    }

    public void setNumero(String numero) {
	this.numero = numero;
    }

    @Column(name = "Mentions", length = 65535)
    public String getMentions() {
	return this.mentions;
    }

    public void setMentions(String mentions) {
	this.mentions = mentions;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "DateFacture", nullable = false, length = 10)
    public Date getDateFacture() {
	return this.dateFacture;
    }

    public void setDateFacture(Date dateFacture) {
	this.dateFacture = dateFacture;
    }

    @OneToMany(fetch = FetchType.EAGER, mappedBy = "factures")
    public Set<Vente> getVentes() {
	return this.ventes;
    }

    public void setVentes(Set<Vente> ventes) {
	this.ventes = ventes;
    }

}
