package fr.jbdev.domaine;

// Generated 7 janv. 2016 21:47:57 by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Produits generated by hbm2java
 */
@Entity
@Table(name = "PRODUITS", catalog = "facturierDeux")
public class Produits implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 1L;
    private Integer numProduits;
    private Entreprises entreprises;
    private Categories categories;
    private Entrepots entrepots;
    private String nom;
    private boolean service;
    private String description;
    private double prixHt;
    private Float stock;
    private Set<Contient> contients = new HashSet<Contient>(0);

    public Produits() {
    }

    public Produits(Entreprises entreprises, Categories categories, String nom,
	    boolean service, String description, double prixHt) {
	this.entreprises = entreprises;
	this.categories = categories;
	this.nom = nom;
	this.service = service;
	this.description = description;
	this.prixHt = prixHt;
    }

    public Produits(Entreprises entreprises, Categories categories,
	    Entrepots entrepots, String nom, boolean service,
	    String description, double prixHt, Float stock,
	    Set<Contient> contients) {
	this.entreprises = entreprises;
	this.categories = categories;
	this.entrepots = entrepots;
	this.nom = nom;
	this.service = service;
	this.description = description;
	this.prixHt = prixHt;
	this.stock = stock;
	this.contients = contients;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "NumProduits", unique = true, nullable = false)
    public Integer getNumProduits() {
	return this.numProduits;
    }

    public void setNumProduits(Integer numProduits) {
	this.numProduits = numProduits;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "NumSiret", nullable = false)
    public Entreprises getEntreprises() {
	return this.entreprises;
    }

    public void setEntreprises(Entreprises entreprises) {
	this.entreprises = entreprises;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "NumCategories", nullable = false)
    public Categories getCategories() {
	return this.categories;
    }

    public void setCategories(Categories categories) {
	this.categories = categories;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "NumEntrepot")
    public Entrepots getEntrepots() {
	return this.entrepots;
    }

    public void setEntrepots(Entrepots entrepots) {
	this.entrepots = entrepots;
    }

    @Column(name = "Nom", nullable = false, length = 25)
    public String getNom() {
	return this.nom;
    }

    public void setNom(String nom) {
	this.nom = nom;
    }

    @Column(name = "Service", nullable = false)
    public boolean isService() {
	return this.service;
    }

    public void setService(boolean service) {
	this.service = service;
    }

    @Column(name = "Description", nullable = false, length = 25)
    public String getDescription() {
	return this.description;
    }

    public void setDescription(String description) {
	this.description = description;
    }

    @Column(name = "PrixHt", nullable = false, precision = 22, scale = 0)
    public double getPrixHt() {
	return this.prixHt;
    }

    public void setPrixHt(double prixHt) {
	this.prixHt = prixHt;
    }

    @Column(name = "Stock", precision = 12, scale = 0)
    public Float getStock() {
	return this.stock;
    }

    public void setStock(Float stock) {
	this.stock = stock;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "produits")
    public Set<Contient> getContients() {
	return this.contients;
    }

    public void setContients(Set<Contient> contients) {
	this.contients = contients;
    }

}
