package fr.jbdev.domaine;

// Generated 7 janv. 2016 21:47:57 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * TauxCotisations generated by hbm2java
 */
@Entity
@Table(name = "TAUX_COTISATIONS", catalog = "facturierDeux")
public class TauxCotisations implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 1L;
    private int numRegime;
    private Regimesocial regimesocial;
    private String cotisations;
    private String baseDeCalcul;
    private Double taux;

    public TauxCotisations() {
    }

    public TauxCotisations(Regimesocial regimesocial, String cotisations,
	    String baseDeCalcul) {
	this.regimesocial = regimesocial;
	this.cotisations = cotisations;
	this.baseDeCalcul = baseDeCalcul;
    }

    public TauxCotisations(Regimesocial regimesocial, String cotisations,
	    String baseDeCalcul, Double taux) {
	this.regimesocial = regimesocial;
	this.cotisations = cotisations;
	this.baseDeCalcul = baseDeCalcul;
	this.taux = taux;
    }

    @GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "regimesocial"))
    @Id
    @GeneratedValue(generator = "generator")
    @Column(name = "NumRegime", unique = true, nullable = false)
    public int getNumRegime() {
	return this.numRegime;
    }

    public void setNumRegime(int numRegime) {
	this.numRegime = numRegime;
    }

    @OneToOne(fetch = FetchType.LAZY)
    @PrimaryKeyJoinColumn
    public Regimesocial getRegimesocial() {
	return this.regimesocial;
    }

    public void setRegimesocial(Regimesocial regimesocial) {
	this.regimesocial = regimesocial;
    }

    @Column(name = "Cotisations", nullable = false, length = 25)
    public String getCotisations() {
	return this.cotisations;
    }

    public void setCotisations(String cotisations) {
	this.cotisations = cotisations;
    }

    @Column(name = "BaseDeCalcul", nullable = false, length = 25)
    public String getBaseDeCalcul() {
	return this.baseDeCalcul;
    }

    public void setBaseDeCalcul(String baseDeCalcul) {
	this.baseDeCalcul = baseDeCalcul;
    }

    @Column(name = "Taux", precision = 22, scale = 0)
    public Double getTaux() {
	return this.taux;
    }

    public void setTaux(Double taux) {
	this.taux = taux;
    }

}
