package fr.jbdev.domaine;

// Generated 7 janv. 2016 21:47:57 by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Todo generated by hbm2java
 */
@Entity
@Table(name = "TODO", catalog = "facturierDeux")
public class Todo implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 1L;
    private Integer numTodo;
    private Utilisateurs utilisateurs;
    private String todo;
    private boolean do_;
    private Date dateDebutTodo;
    private Date dateFinTodo;
    private Date tempAvantRappel;

    public Todo() {
    }

    public Todo(String todo, boolean do_, Date dateDebutTodo, Date dateFinTodo) {
	this.todo = todo;
	this.do_ = do_;
	this.dateDebutTodo = dateDebutTodo;
	this.dateFinTodo = dateFinTodo;
    }

    public Todo(Utilisateurs utilisateurs, String todo, boolean do_,
	    Date dateDebutTodo, Date dateFinTodo, Date tempAvantRappel) {
	this.utilisateurs = utilisateurs;
	this.todo = todo;
	this.do_ = do_;
	this.dateDebutTodo = dateDebutTodo;
	this.dateFinTodo = dateFinTodo;
	this.tempAvantRappel = tempAvantRappel;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "NumTodo", unique = true, nullable = false)
    public Integer getNumTodo() {
	return this.numTodo;
    }

    public void setNumTodo(Integer numTodo) {
	this.numTodo = numTodo;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "NumUser")
    public Utilisateurs getUtilisateurs() {
	return this.utilisateurs;
    }

    public void setUtilisateurs(Utilisateurs utilisateurs) {
	this.utilisateurs = utilisateurs;
    }

    @Column(name = "Todo", nullable = false, length = 65535)
    public String getTodo() {
	return this.todo;
    }

    public void setTodo(String todo) {
	this.todo = todo;
    }

    @Column(name = "Do", nullable = false)
    public boolean isDo_() {
	return this.do_;
    }

    public void setDo_(boolean do_) {
	this.do_ = do_;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "DateDebutTodo", nullable = false, length = 10)
    public Date getDateDebutTodo() {
	return this.dateDebutTodo;
    }

    public void setDateDebutTodo(Date dateDebutTodo) {
	this.dateDebutTodo = dateDebutTodo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "DateFinTodo", nullable = false, length = 10)
    public Date getDateFinTodo() {
	return this.dateFinTodo;
    }

    public void setDateFinTodo(Date dateFinTodo) {
	this.dateFinTodo = dateFinTodo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "TempAvantRappel", length = 10)
    public Date getTempAvantRappel() {
	return this.tempAvantRappel;
    }

    public void setTempAvantRappel(Date tempAvantRappel) {
	this.tempAvantRappel = tempAvantRappel;
    }

}
