package fr.jbdev.domaine;

// Generated 7 janv. 2016 21:47:57 by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TypeDePaiment generated by hbm2java
 */
@Entity
@Table(name = "TYPE_DE_PAIMENT", catalog = "facturierDeux")
public class TypeDePaiment implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 1L;
    private Integer numTypeDePaiment;
    private String nom;
    private String description;
    private Set<Vente> ventes = new HashSet<Vente>(0);
    private Set<Achats> achatses = new HashSet<Achats>(0);

    public TypeDePaiment() {
    }

    public TypeDePaiment(String nom, String description) {
	this.nom = nom;
	this.description = description;
    }

    public TypeDePaiment(String nom, String description, Set<Vente> ventes,
	    Set<Achats> achatses) {
	this.nom = nom;
	this.description = description;
	this.ventes = ventes;
	this.achatses = achatses;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "NumTypeDePaiment", unique = true, nullable = false)
    public Integer getNumTypeDePaiment() {
	return this.numTypeDePaiment;
    }

    public void setNumTypeDePaiment(Integer numTypeDePaiment) {
	this.numTypeDePaiment = numTypeDePaiment;
    }

    @Column(name = "Nom", nullable = false, length = 25)
    public String getNom() {
	return this.nom;
    }

    public void setNom(String nom) {
	this.nom = nom;
    }

    @Column(name = "Description", nullable = false, length = 65535)
    public String getDescription() {
	return this.description;
    }

    public void setDescription(String description) {
	this.description = description;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "typeDePaiment")
    public Set<Vente> getVentes() {
	return this.ventes;
    }

    public void setVentes(Set<Vente> ventes) {
	this.ventes = ventes;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "typeDePaiment")
    public Set<Achats> getAchatses() {
	return this.achatses;
    }

    public void setAchatses(Set<Achats> achatses) {
	this.achatses = achatses;
    }

}
