package fr.jbdev.domaine;

// Generated 7 janv. 2016 21:47:57 by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Utilisateurs generated by hbm2java
 */
@Entity
@Table(name = "UTILISATEURS", catalog = "facturierDeux")
public class Utilisateurs implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 1L;
    private Integer numUser;
    private Personnes personnes;
    private Entreprises entreprises;
    private String email;
    private String passWord;
    private boolean enabled;
    private boolean premium;
    private boolean responsable;
    private boolean verifie;
    private String role;
    private Set<Todo> todos = new HashSet<Todo>(0);

    public Utilisateurs() {
    }

    public Utilisateurs(Personnes personnes, Entreprises entreprises,
	    String email, String passWord, boolean enabled, boolean premium,
	    boolean responsable, boolean verifie, String role) {
	this.personnes = personnes;
	this.entreprises = entreprises;
	this.email = email;
	this.passWord = passWord;
	this.enabled = enabled;
	this.premium = premium;
	this.responsable = responsable;
	this.verifie = verifie;
	this.role = role;
    }

    public Utilisateurs(Personnes personnes, Entreprises entreprises,
	    String email, String passWord, boolean enabled, boolean premium,
	    boolean responsable, boolean verifie, String role, Set<Todo> todos) {
	this.personnes = personnes;
	this.entreprises = entreprises;
	this.email = email;
	this.passWord = passWord;
	this.enabled = enabled;
	this.premium = premium;
	this.responsable = responsable;
	this.verifie = verifie;
	this.role = role;
	this.todos = todos;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "NumUser", unique = true, nullable = false)
    public Integer getNumUser() {
	return this.numUser;
    }

    public void setNumUser(Integer numUser) {
	this.numUser = numUser;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "NumPersonne", nullable = false)
    public Personnes getPersonnes() {
	return this.personnes;
    }

    public void setPersonnes(Personnes personnes) {
	this.personnes = personnes;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "NumSiret", nullable = false)
    public Entreprises getEntreprises() {
	return this.entreprises;
    }

    public void setEntreprises(Entreprises entreprises) {
	this.entreprises = entreprises;
    }

    @Column(name = "Email", nullable = false, length = 128)
    public String getEmail() {
	return this.email;
    }

    public void setEmail(String email) {
	this.email = email;
    }

    @Column(name = "PassWord", nullable = false, length = 258)
    public String getPassWord() {
	return this.passWord;
    }

    public void setPassWord(String passWord) {
	this.passWord = passWord;
    }

    @Column(name = "Enabled", nullable = false)
    public boolean isEnabled() {
	return this.enabled;
    }

    public void setEnabled(boolean enabled) {
	this.enabled = enabled;
    }

    @Column(name = "Premium", nullable = false)
    public boolean isPremium() {
	return this.premium;
    }

    public void setPremium(boolean premium) {
	this.premium = premium;
    }

    @Column(name = "Responsable", nullable = false)
    public boolean isResponsable() {
	return this.responsable;
    }

    public void setResponsable(boolean responsable) {
	this.responsable = responsable;
    }

    @Column(name = "Verifie", nullable = false)
    public boolean isVerifie() {
	return this.verifie;
    }

    public void setVerifie(boolean verifie) {
	this.verifie = verifie;
    }

    @Column(name = "Role", nullable = false, length = 25)
    public String getRole() {
	return this.role;
    }

    public void setRole(String role) {
	this.role = role;
    }

    @OneToMany(fetch = FetchType.EAGER, mappedBy = "utilisateurs")
    public Set<Todo> getTodos() {
	return this.todos;
    }

    public void setTodos(Set<Todo> todos) {
	this.todos = todos;
    }

}
