package fr.jbdev.domaine;

// Generated 7 janv. 2016 21:47:57 by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Vente generated by hbm2java
 */
@Entity
@Table(name = "VENTE", catalog = "facturierDeux")
public class Vente implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 1L;
    private Integer numVente;
    private TypeDePaiment typeDePaiment;
    private Factures factures;
    private double accompte;
    private Date dateVente;
    private Double tvaCumule;

    public Vente() {
    }

    public Vente(TypeDePaiment typeDePaiment, Factures factures,
	    double accompte, Date dateVente) {
	this.typeDePaiment = typeDePaiment;
	this.factures = factures;
	this.accompte = accompte;
	this.dateVente = dateVente;
    }

    public Vente(TypeDePaiment typeDePaiment, Factures factures,
	    double accompte, Date dateVente, Double tvaCumule) {
	this.typeDePaiment = typeDePaiment;
	this.factures = factures;
	this.accompte = accompte;
	this.dateVente = dateVente;
	this.tvaCumule = tvaCumule;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "NumVente", unique = true, nullable = false)
    public Integer getNumVente() {
	return this.numVente;
    }

    public void setNumVente(Integer numVente) {
	this.numVente = numVente;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "NumTypeDePaiment", nullable = false)
    public TypeDePaiment getTypeDePaiment() {
	return this.typeDePaiment;
    }

    public void setTypeDePaiment(TypeDePaiment typeDePaiment) {
	this.typeDePaiment = typeDePaiment;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "NumFacture", nullable = false)
    public Factures getFactures() {
	return this.factures;
    }

    public void setFactures(Factures factures) {
	this.factures = factures;
    }

    @Column(name = "Accompte", nullable = false, precision = 22, scale = 0)
    public double getAccompte() {
	return this.accompte;
    }

    public void setAccompte(double accompte) {
	this.accompte = accompte;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "DateVente", nullable = false, length = 10)
    public Date getDateVente() {
	return this.dateVente;
    }

    public void setDateVente(Date dateVente) {
	this.dateVente = dateVente;
    }

    @Column(name = "TvaCumule", precision = 22, scale = 0)
    public Double getTvaCumule() {
	return this.tvaCumule;
    }

    public void setTvaCumule(Double tvaCumule) {
	this.tvaCumule = tvaCumule;
    }

}
